
name: git-log

on:
  schedule:
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Interate through repos, capture git log with pretty print
        run: ./github/scripts/git-log.sh -o casa-vega -t ${{ steps.generate_token.outputs.token }}
