
name: git-log

on:
  schedule:
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  git-log-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Iterate through repos, capture git log with pretty print
        run: bash .github/scripts/git-log.sh -o casa-vega -t ${{ steps.generate_token.outputs.token }}
      - name: Archive log folder
        run: tar -czvf git-log-archive.tar.gz logs/
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: git-log-archive.tar.gz
          path: git-log-archive.tar.gz
          retention: 8 days
